
package sandboxwebapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicePort", targetNamespace = "urn:SandboxWebApi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePort {


    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoAddDescToItemsResponse
     */
    @WebMethod(action = "#doAddDescToItems")
    @WebResult(name = "doAddDescToItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoAddDescToItemsResponse doAddDescToItems(
        @WebParam(name = "DoAddDescToItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoAddDescToItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoAddPackageInfoToPostBuyFormResponse
     */
    @WebMethod(action = "#doAddPackageInfoToPostBuyForm")
    @WebResult(name = "doAddPackageInfoToPostBuyFormResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoAddPackageInfoToPostBuyFormResponse doAddPackageInfoToPostBuyForm(
        @WebParam(name = "DoAddPackageInfoToPostBuyFormRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoAddPackageInfoToPostBuyFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoAddToBlackListResponse
     */
    @WebMethod(action = "#doAddToBlackList")
    @WebResult(name = "doAddToBlackListResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoAddToBlackListResponse doAddToBlackList(
        @WebParam(name = "DoAddToBlackListRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoAddToBlackListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoBidItemResponse
     */
    @WebMethod(action = "#doBidItem")
    @WebResult(name = "doBidItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoBidItemResponse doBidItem(
        @WebParam(name = "DoBidItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoBidItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCancelBidItemResponse
     */
    @WebMethod(action = "#doCancelBidItem")
    @WebResult(name = "doCancelBidItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCancelBidItemResponse doCancelBidItem(
        @WebParam(name = "DoCancelBidItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCancelBidItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCancelRefundFormResponse
     */
    @WebMethod(action = "#doCancelRefundForm")
    @WebResult(name = "doCancelRefundFormResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCancelRefundFormResponse doCancelRefundForm(
        @WebParam(name = "DoCancelRefundFormRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCancelRefundFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCancelRefundWarningResponse
     */
    @WebMethod(action = "#doCancelRefundWarning")
    @WebResult(name = "doCancelRefundWarningResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCancelRefundWarningResponse doCancelRefundWarning(
        @WebParam(name = "DoCancelRefundWarningRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCancelRefundWarningRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCancelTransactionResponse
     */
    @WebMethod(action = "#doCancelTransaction")
    @WebResult(name = "doCancelTransactionResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCancelTransactionResponse doCancelTransaction(
        @WebParam(name = "DoCancelTransactionRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCancelTransactionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoChangeItemFieldsResponse
     */
    @WebMethod(action = "#doChangeItemFields")
    @WebResult(name = "doChangeItemFieldsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoChangeItemFieldsResponse doChangeItemFields(
        @WebParam(name = "DoChangeItemFieldsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoChangeItemFieldsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoChangePriceItemResponse
     */
    @WebMethod(action = "#doChangePriceItem")
    @WebResult(name = "doChangePriceItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoChangePriceItemResponse doChangePriceItem(
        @WebParam(name = "DoChangePriceItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoChangePriceItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoChangeQuantityItemResponse
     */
    @WebMethod(action = "#doChangeQuantityItem")
    @WebResult(name = "doChangeQuantityItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoChangeQuantityItemResponse doChangeQuantityItem(
        @WebParam(name = "DoChangeQuantityItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoChangeQuantityItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCheckItemDescriptionResponse
     */
    @WebMethod(action = "#doCheckItemDescription")
    @WebResult(name = "doCheckItemDescriptionResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCheckItemDescriptionResponse doCheckItemDescription(
        @WebParam(name = "DoCheckItemDescriptionRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCheckItemDescriptionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCheckNewAuctionExtResponse
     */
    @WebMethod(action = "#doCheckNewAuctionExt")
    @WebResult(name = "doCheckNewAuctionExtResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCheckNewAuctionExtResponse doCheckNewAuctionExt(
        @WebParam(name = "DoCheckNewAuctionExtRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCheckNewAuctionExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoCreateItemTemplateResponse
     */
    @WebMethod(action = "#doCreateItemTemplate")
    @WebResult(name = "doCreateItemTemplateResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoCreateItemTemplateResponse doCreateItemTemplate(
        @WebParam(name = "DoCreateItemTemplateRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoCreateItemTemplateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoFeedbackResponse
     */
    @WebMethod(action = "#doFeedback")
    @WebResult(name = "doFeedbackResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoFeedbackResponse doFeedback(
        @WebParam(name = "DoFeedbackRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoFeedbackRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoFeedbackManyResponse
     */
    @WebMethod(action = "#doFeedbackMany")
    @WebResult(name = "doFeedbackManyResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoFeedbackManyResponse doFeedbackMany(
        @WebParam(name = "DoFeedbackManyRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoFeedbackManyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoFinishItemResponse
     */
    @WebMethod(action = "#doFinishItem")
    @WebResult(name = "doFinishItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoFinishItemResponse doFinishItem(
        @WebParam(name = "DoFinishItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoFinishItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoFinishItemsResponse
     */
    @WebMethod(action = "#doFinishItems")
    @WebResult(name = "doFinishItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoFinishItemsResponse doFinishItems(
        @WebParam(name = "DoFinishItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoFinishItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetAdminUserLicenceDateResponse
     */
    @WebMethod(action = "#doGetAdminUserLicenceDate")
    @WebResult(name = "doGetAdminUserLicenceDateResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetAdminUserLicenceDateResponse doGetAdminUserLicenceDate(
        @WebParam(name = "DoGetAdminUserLicenceDateRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetAdminUserLicenceDateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetArchiveRefundsListResponse
     */
    @WebMethod(action = "#doGetArchiveRefundsList")
    @WebResult(name = "doGetArchiveRefundsListResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetArchiveRefundsListResponse doGetArchiveRefundsList(
        @WebParam(name = "DoGetArchiveRefundsListRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetArchiveRefundsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetBidItem2Response
     */
    @WebMethod(action = "#doGetBidItem2")
    @WebResult(name = "doGetBidItem2Response", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetBidItem2Response doGetBidItem2(
        @WebParam(name = "DoGetBidItem2Request", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetBidItem2Request parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetBlackListUsersResponse
     */
    @WebMethod(action = "#doGetBlackListUsers")
    @WebResult(name = "doGetBlackListUsersResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetBlackListUsersResponse doGetBlackListUsers(
        @WebParam(name = "DoGetBlackListUsersRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetBlackListUsersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetCategoryPathResponse
     */
    @WebMethod(action = "#doGetCategoryPath")
    @WebResult(name = "doGetCategoryPathResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetCategoryPathResponse doGetCategoryPath(
        @WebParam(name = "DoGetCategoryPathRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetCategoryPathRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetCatsDataResponse
     */
    @WebMethod(action = "#doGetCatsData")
    @WebResult(name = "doGetCatsDataResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetCatsDataResponse doGetCatsData(
        @WebParam(name = "DoGetCatsDataRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetCatsDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetCatsDataCountResponse
     */
    @WebMethod(action = "#doGetCatsDataCount")
    @WebResult(name = "doGetCatsDataCountResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetCatsDataCountResponse doGetCatsDataCount(
        @WebParam(name = "DoGetCatsDataCountRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetCatsDataCountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetCatsDataLimitResponse
     */
    @WebMethod(action = "#doGetCatsDataLimit")
    @WebResult(name = "doGetCatsDataLimitResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetCatsDataLimitResponse doGetCatsDataLimit(
        @WebParam(name = "DoGetCatsDataLimitRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetCatsDataLimitRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetCountriesResponse
     */
    @WebMethod(action = "#doGetCountries")
    @WebResult(name = "doGetCountriesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetCountriesResponse doGetCountries(
        @WebParam(name = "DoGetCountriesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetCountriesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetDealsResponse
     */
    @WebMethod(action = "#doGetDeals")
    @WebResult(name = "doGetDealsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetDealsResponse doGetDeals(
        @WebParam(name = "DoGetDealsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetFavouriteCategoriesResponse
     */
    @WebMethod(action = "#doGetFavouriteCategories")
    @WebResult(name = "doGetFavouriteCategoriesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetFavouriteCategoriesResponse doGetFavouriteCategories(
        @WebParam(name = "DoGetFavouriteCategoriesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetFavouriteCategoriesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetFavouriteSellersResponse
     */
    @WebMethod(action = "#doGetFavouriteSellers")
    @WebResult(name = "doGetFavouriteSellersResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetFavouriteSellersResponse doGetFavouriteSellers(
        @WebParam(name = "DoGetFavouriteSellersRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetFavouriteSellersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetFeedbackResponse
     */
    @WebMethod(action = "#doGetFeedback")
    @WebResult(name = "doGetFeedbackResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetFeedbackResponse doGetFeedback(
        @WebParam(name = "DoGetFeedbackRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetFeedbackRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetFilledPostBuyFormsResponse
     */
    @WebMethod(action = "#doGetFilledPostBuyForms")
    @WebResult(name = "doGetFilledPostBuyFormsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetFilledPostBuyFormsResponse doGetFilledPostBuyForms(
        @WebParam(name = "DoGetFilledPostBuyFormsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetFilledPostBuyFormsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetFreeDeliveryAmountResponse
     */
    @WebMethod(action = "#doGetFreeDeliveryAmount")
    @WebResult(name = "doGetFreeDeliveryAmountResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetFreeDeliveryAmountResponse doGetFreeDeliveryAmount(
        @WebParam(name = "DoGetFreeDeliveryAmountRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetFreeDeliveryAmountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetItemFieldsResponse
     */
    @WebMethod(action = "#doGetItemFields")
    @WebResult(name = "doGetItemFieldsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetItemFieldsResponse doGetItemFields(
        @WebParam(name = "DoGetItemFieldsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetItemFieldsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetItemTemplatesResponse
     */
    @WebMethod(action = "#doGetItemTemplates")
    @WebResult(name = "doGetItemTemplatesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetItemTemplatesResponse doGetItemTemplates(
        @WebParam(name = "DoGetItemTemplatesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetItemTemplatesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetItemsInfoResponse
     */
    @WebMethod(action = "#doGetItemsInfo")
    @WebResult(name = "doGetItemsInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetItemsInfoResponse doGetItemsInfo(
        @WebParam(name = "DoGetItemsInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetItemsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetItemsListResponse
     */
    @WebMethod(action = "#doGetItemsList")
    @WebResult(name = "doGetItemsListResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetItemsListResponse doGetItemsList(
        @WebParam(name = "DoGetItemsListRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetItemsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMessageToBuyerResponse
     */
    @WebMethod(action = "#doGetMessageToBuyer")
    @WebResult(name = "doGetMessageToBuyerResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMessageToBuyerResponse doGetMessageToBuyer(
        @WebParam(name = "DoGetMessageToBuyerRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMessageToBuyerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyAddressesResponse
     */
    @WebMethod(action = "#doGetMyAddresses")
    @WebResult(name = "doGetMyAddressesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyAddressesResponse doGetMyAddresses(
        @WebParam(name = "DoGetMyAddressesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyAddressesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyBidItemsResponse
     */
    @WebMethod(action = "#doGetMyBidItems")
    @WebResult(name = "doGetMyBidItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyBidItemsResponse doGetMyBidItems(
        @WebParam(name = "DoGetMyBidItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyBidItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyCurrentShipmentPriceTypeResponse
     */
    @WebMethod(action = "#doGetMyCurrentShipmentPriceType")
    @WebResult(name = "doGetMyCurrentShipmentPriceTypeResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyCurrentShipmentPriceTypeResponse doGetMyCurrentShipmentPriceType(
        @WebParam(name = "DoGetMyCurrentShipmentPriceTypeRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyCurrentShipmentPriceTypeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyDataResponse
     */
    @WebMethod(action = "#doGetMyData")
    @WebResult(name = "doGetMyDataResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyDataResponse doGetMyData(
        @WebParam(name = "DoGetMyDataRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyFutureItemsResponse
     */
    @WebMethod(action = "#doGetMyFutureItems")
    @WebResult(name = "doGetMyFutureItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyFutureItemsResponse doGetMyFutureItems(
        @WebParam(name = "DoGetMyFutureItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyFutureItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyIncomingPaymentsResponse
     */
    @WebMethod(action = "#doGetMyIncomingPayments")
    @WebResult(name = "doGetMyIncomingPaymentsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyIncomingPaymentsResponse doGetMyIncomingPayments(
        @WebParam(name = "DoGetMyIncomingPaymentsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyIncomingPaymentsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyIncomingPaymentsRefundsResponse
     */
    @WebMethod(action = "#doGetMyIncomingPaymentsRefunds")
    @WebResult(name = "doGetMyIncomingPaymentsRefundsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyIncomingPaymentsRefundsResponse doGetMyIncomingPaymentsRefunds(
        @WebParam(name = "DoGetMyIncomingPaymentsRefundsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyIncomingPaymentsRefundsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyNotSoldItemsResponse
     */
    @WebMethod(action = "#doGetMyNotSoldItems")
    @WebResult(name = "doGetMyNotSoldItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyNotSoldItemsResponse doGetMyNotSoldItems(
        @WebParam(name = "DoGetMyNotSoldItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyNotSoldItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyNotWonItemsResponse
     */
    @WebMethod(action = "#doGetMyNotWonItems")
    @WebResult(name = "doGetMyNotWonItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyNotWonItemsResponse doGetMyNotWonItems(
        @WebParam(name = "DoGetMyNotWonItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyNotWonItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyPaymentsResponse
     */
    @WebMethod(action = "#doGetMyPayments")
    @WebResult(name = "doGetMyPaymentsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyPaymentsResponse doGetMyPayments(
        @WebParam(name = "DoGetMyPaymentsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyPaymentsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyPaymentsInfoResponse
     */
    @WebMethod(action = "#doGetMyPaymentsInfo")
    @WebResult(name = "doGetMyPaymentsInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyPaymentsInfoResponse doGetMyPaymentsInfo(
        @WebParam(name = "DoGetMyPaymentsInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyPaymentsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyPaymentsRefundsResponse
     */
    @WebMethod(action = "#doGetMyPaymentsRefunds")
    @WebResult(name = "doGetMyPaymentsRefundsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyPaymentsRefundsResponse doGetMyPaymentsRefunds(
        @WebParam(name = "DoGetMyPaymentsRefundsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyPaymentsRefundsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyPayoutsResponse
     */
    @WebMethod(action = "#doGetMyPayouts")
    @WebResult(name = "doGetMyPayoutsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyPayoutsResponse doGetMyPayouts(
        @WebParam(name = "DoGetMyPayoutsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyPayoutsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMySellItemsResponse
     */
    @WebMethod(action = "#doGetMySellItems")
    @WebResult(name = "doGetMySellItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMySellItemsResponse doGetMySellItems(
        @WebParam(name = "DoGetMySellItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMySellItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMySellRatingResponse
     */
    @WebMethod(action = "#doGetMySellRating")
    @WebResult(name = "doGetMySellRatingResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMySellRatingResponse doGetMySellRating(
        @WebParam(name = "DoGetMySellRatingRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMySellRatingRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMySoldItemsResponse
     */
    @WebMethod(action = "#doGetMySoldItems")
    @WebResult(name = "doGetMySoldItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMySoldItemsResponse doGetMySoldItems(
        @WebParam(name = "DoGetMySoldItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMySoldItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetMyWonItemsResponse
     */
    @WebMethod(action = "#doGetMyWonItems")
    @WebResult(name = "doGetMyWonItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetMyWonItemsResponse doGetMyWonItems(
        @WebParam(name = "DoGetMyWonItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetMyWonItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPaymentDataResponse
     */
    @WebMethod(action = "#doGetPaymentData")
    @WebResult(name = "doGetPaymentDataResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPaymentDataResponse doGetPaymentData(
        @WebParam(name = "DoGetPaymentDataRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPaymentDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPaymentMethodsResponse
     */
    @WebMethod(action = "#doGetPaymentMethods")
    @WebResult(name = "doGetPaymentMethodsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPaymentMethodsResponse doGetPaymentMethods(
        @WebParam(name = "DoGetPaymentMethodsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPaymentMethodsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPostBuyDataResponse
     */
    @WebMethod(action = "#doGetPostBuyData")
    @WebResult(name = "doGetPostBuyDataResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPostBuyDataResponse doGetPostBuyData(
        @WebParam(name = "DoGetPostBuyDataRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPostBuyDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPostBuyFormsDataForBuyersResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsDataForBuyers")
    @WebResult(name = "doGetPostBuyFormsDataForBuyersResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPostBuyFormsDataForBuyersResponse doGetPostBuyFormsDataForBuyers(
        @WebParam(name = "DoGetPostBuyFormsDataForBuyersRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPostBuyFormsDataForBuyersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPostBuyFormsDataForSellersResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsDataForSellers")
    @WebResult(name = "doGetPostBuyFormsDataForSellersResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPostBuyFormsDataForSellersResponse doGetPostBuyFormsDataForSellers(
        @WebParam(name = "DoGetPostBuyFormsDataForSellersRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPostBuyFormsDataForSellersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPostBuyFormsIdsResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsIds")
    @WebResult(name = "doGetPostBuyFormsIdsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPostBuyFormsIdsResponse doGetPostBuyFormsIds(
        @WebParam(name = "DoGetPostBuyFormsIdsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPostBuyFormsIdsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetPostBuyItemInfoResponse
     */
    @WebMethod(action = "#doGetPostBuyItemInfo")
    @WebResult(name = "doGetPostBuyItemInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetPostBuyItemInfoResponse doGetPostBuyItemInfo(
        @WebParam(name = "DoGetPostBuyItemInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetPostBuyItemInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetRefundsDealsResponse
     */
    @WebMethod(action = "#doGetRefundsDeals")
    @WebResult(name = "doGetRefundsDealsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetRefundsDealsResponse doGetRefundsDeals(
        @WebParam(name = "DoGetRefundsDealsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetRefundsDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetRefundsListResponse
     */
    @WebMethod(action = "#doGetRefundsList")
    @WebResult(name = "doGetRefundsListResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetRefundsListResponse doGetRefundsList(
        @WebParam(name = "DoGetRefundsListRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetRefundsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetRefundsReasonsResponse
     */
    @WebMethod(action = "#doGetRefundsReasons")
    @WebResult(name = "doGetRefundsReasonsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetRefundsReasonsResponse doGetRefundsReasons(
        @WebParam(name = "DoGetRefundsReasonsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetRefundsReasonsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetRelatedItemsResponse
     */
    @WebMethod(action = "#doGetRelatedItems")
    @WebResult(name = "doGetRelatedItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetRelatedItemsResponse doGetRelatedItems(
        @WebParam(name = "DoGetRelatedItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetRelatedItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSellFormAttribsResponse
     */
    @WebMethod(action = "#doGetSellFormAttribs")
    @WebResult(name = "doGetSellFormAttribsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSellFormAttribsResponse doGetSellFormAttribs(
        @WebParam(name = "DoGetSellFormAttribsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSellFormAttribsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSellFormFieldsExtResponse
     */
    @WebMethod(action = "#doGetSellFormFieldsExt")
    @WebResult(name = "doGetSellFormFieldsExtResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSellFormFieldsExtResponse doGetSellFormFieldsExt(
        @WebParam(name = "DoGetSellFormFieldsExtRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSellFormFieldsExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSellFormFieldsExtLimitResponse
     */
    @WebMethod(action = "#doGetSellFormFieldsExtLimit")
    @WebResult(name = "doGetSellFormFieldsExtLimitResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSellFormFieldsExtLimitResponse doGetSellFormFieldsExtLimit(
        @WebParam(name = "DoGetSellFormFieldsExtLimitRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSellFormFieldsExtLimitRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSellFormFieldsForCategoryResponse
     */
    @WebMethod(action = "#doGetSellFormFieldsForCategory")
    @WebResult(name = "doGetSellFormFieldsForCategoryResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSellFormFieldsForCategoryResponse doGetSellFormFieldsForCategory(
        @WebParam(name = "DoGetSellFormFieldsForCategoryRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSellFormFieldsForCategoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSellRatingReasonsResponse
     */
    @WebMethod(action = "#doGetSellRatingReasons")
    @WebResult(name = "doGetSellRatingReasonsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSellRatingReasonsResponse doGetSellRatingReasons(
        @WebParam(name = "DoGetSellRatingReasonsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSellRatingReasonsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetShipmentDataResponse
     */
    @WebMethod(action = "#doGetShipmentData")
    @WebResult(name = "doGetShipmentDataResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetShipmentDataResponse doGetShipmentData(
        @WebParam(name = "DoGetShipmentDataRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetShipmentDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetShipmentDataForRelatedItemsResponse
     */
    @WebMethod(action = "#doGetShipmentDataForRelatedItems")
    @WebResult(name = "doGetShipmentDataForRelatedItemsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetShipmentDataForRelatedItemsResponse doGetShipmentDataForRelatedItems(
        @WebParam(name = "DoGetShipmentDataForRelatedItemsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetShipmentDataForRelatedItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetShipmentPriceTypesResponse
     */
    @WebMethod(action = "#doGetShipmentPriceTypes")
    @WebResult(name = "doGetShipmentPriceTypesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetShipmentPriceTypesResponse doGetShipmentPriceTypes(
        @WebParam(name = "DoGetShipmentPriceTypesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetShipmentPriceTypesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetShopsTagsResponse
     */
    @WebMethod(action = "#doGetShopsTags")
    @WebResult(name = "doGetShopsTagsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetShopsTagsResponse doGetShopsTags(
        @WebParam(name = "DoGetShopsTagsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetShopsTagsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSiteJournalResponse
     */
    @WebMethod(action = "#doGetSiteJournal")
    @WebResult(name = "doGetSiteJournalResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSiteJournalResponse doGetSiteJournal(
        @WebParam(name = "DoGetSiteJournalRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSiteJournalRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSiteJournalDealsResponse
     */
    @WebMethod(action = "#doGetSiteJournalDeals")
    @WebResult(name = "doGetSiteJournalDealsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSiteJournalDealsResponse doGetSiteJournalDeals(
        @WebParam(name = "DoGetSiteJournalDealsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSiteJournalDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSiteJournalDealsInfoResponse
     */
    @WebMethod(action = "#doGetSiteJournalDealsInfo")
    @WebResult(name = "doGetSiteJournalDealsInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSiteJournalDealsInfoResponse doGetSiteJournalDealsInfo(
        @WebParam(name = "DoGetSiteJournalDealsInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSiteJournalDealsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSiteJournalInfoResponse
     */
    @WebMethod(action = "#doGetSiteJournalInfo")
    @WebResult(name = "doGetSiteJournalInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSiteJournalInfoResponse doGetSiteJournalInfo(
        @WebParam(name = "DoGetSiteJournalInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSiteJournalInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetStatesInfoResponse
     */
    @WebMethod(action = "#doGetStatesInfo")
    @WebResult(name = "doGetStatesInfoResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetStatesInfoResponse doGetStatesInfo(
        @WebParam(name = "DoGetStatesInfoRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetStatesInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetSystemTimeResponse
     */
    @WebMethod(action = "#doGetSystemTime")
    @WebResult(name = "doGetSystemTimeResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetSystemTimeResponse doGetSystemTime(
        @WebParam(name = "DoGetSystemTimeRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetSystemTimeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetTransactionsIDsResponse
     */
    @WebMethod(action = "#doGetTransactionsIDs")
    @WebResult(name = "doGetTransactionsIDsResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetTransactionsIDsResponse doGetTransactionsIDs(
        @WebParam(name = "DoGetTransactionsIDsRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetTransactionsIDsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetUserIDResponse
     */
    @WebMethod(action = "#doGetUserID")
    @WebResult(name = "doGetUserIDResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetUserIDResponse doGetUserID(
        @WebParam(name = "DoGetUserIDRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetUserIDRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetUserLicenceDateResponse
     */
    @WebMethod(action = "#doGetUserLicenceDate")
    @WebResult(name = "doGetUserLicenceDateResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetUserLicenceDateResponse doGetUserLicenceDate(
        @WebParam(name = "DoGetUserLicenceDateRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetUserLicenceDateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetUserLoginResponse
     */
    @WebMethod(action = "#doGetUserLogin")
    @WebResult(name = "doGetUserLoginResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetUserLoginResponse doGetUserLogin(
        @WebParam(name = "DoGetUserLoginRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetUserLoginRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetWaitingFeedbacksResponse
     */
    @WebMethod(action = "#doGetWaitingFeedbacks")
    @WebResult(name = "doGetWaitingFeedbacksResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetWaitingFeedbacksResponse doGetWaitingFeedbacks(
        @WebParam(name = "DoGetWaitingFeedbacksRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetWaitingFeedbacksRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoGetWaitingFeedbacksCountResponse
     */
    @WebMethod(action = "#doGetWaitingFeedbacksCount")
    @WebResult(name = "doGetWaitingFeedbacksCountResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoGetWaitingFeedbacksCountResponse doGetWaitingFeedbacksCount(
        @WebParam(name = "DoGetWaitingFeedbacksCountRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoGetWaitingFeedbacksCountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoLoginResponse
     */
    @WebMethod(action = "#doLogin")
    @WebResult(name = "doLoginResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoLoginResponse doLogin(
        @WebParam(name = "DoLoginRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoLoginRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoLoginEncResponse
     */
    @WebMethod(action = "#doLoginEnc")
    @WebResult(name = "doLoginEncResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoLoginEncResponse doLoginEnc(
        @WebParam(name = "DoLoginEncRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoLoginEncRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoLoginWithAccessTokenResponse
     */
    @WebMethod(action = "#doLoginWithAccessToken")
    @WebResult(name = "doLoginWithAccessTokenResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoLoginWithAccessTokenResponse doLoginWithAccessToken(
        @WebParam(name = "DoLoginWithAccessTokenRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoLoginWithAccessTokenRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyAccount2Response
     */
    @WebMethod(action = "#doMyAccount2")
    @WebResult(name = "doMyAccount2Response", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyAccount2Response doMyAccount2(
        @WebParam(name = "DoMyAccount2Request", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyAccount2Request parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyAccountItemsCountResponse
     */
    @WebMethod(action = "#doMyAccountItemsCount")
    @WebResult(name = "doMyAccountItemsCountResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyAccountItemsCountResponse doMyAccountItemsCount(
        @WebParam(name = "DoMyAccountItemsCountRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyAccountItemsCountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyBillingResponse
     */
    @WebMethod(action = "#doMyBilling")
    @WebResult(name = "doMyBillingResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyBillingResponse doMyBilling(
        @WebParam(name = "DoMyBillingRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyBillingRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyBillingItemResponse
     */
    @WebMethod(action = "#doMyBillingItem")
    @WebResult(name = "doMyBillingItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyBillingItemResponse doMyBillingItem(
        @WebParam(name = "DoMyBillingItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyBillingItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyContactResponse
     */
    @WebMethod(action = "#doMyContact")
    @WebResult(name = "doMyContactResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyContactResponse doMyContact(
        @WebParam(name = "DoMyContactRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyContactRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyFeedback2Response
     */
    @WebMethod(action = "#doMyFeedback2")
    @WebResult(name = "doMyFeedback2Response", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyFeedback2Response doMyFeedback2(
        @WebParam(name = "DoMyFeedback2Request", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyFeedback2Request parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoMyFeedback2LimitResponse
     */
    @WebMethod(action = "#doMyFeedback2Limit")
    @WebResult(name = "doMyFeedback2LimitResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoMyFeedback2LimitResponse doMyFeedback2Limit(
        @WebParam(name = "DoMyFeedback2LimitRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoMyFeedback2LimitRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoNewAuctionExtResponse
     */
    @WebMethod(action = "#doNewAuctionExt")
    @WebResult(name = "doNewAuctionExtResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoNewAuctionExtResponse doNewAuctionExt(
        @WebParam(name = "DoNewAuctionExtRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoNewAuctionExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoQueryAllSysStatusResponse
     */
    @WebMethod(action = "#doQueryAllSysStatus")
    @WebResult(name = "doQueryAllSysStatusResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoQueryAllSysStatusResponse doQueryAllSysStatus(
        @WebParam(name = "DoQueryAllSysStatusRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoQueryAllSysStatusRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoQuerySysStatusResponse
     */
    @WebMethod(action = "#doQuerySysStatus")
    @WebResult(name = "doQuerySysStatusResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoQuerySysStatusResponse doQuerySysStatus(
        @WebParam(name = "DoQuerySysStatusRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoQuerySysStatusRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoRemoveFromBlackListResponse
     */
    @WebMethod(action = "#doRemoveFromBlackList")
    @WebResult(name = "doRemoveFromBlackListResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoRemoveFromBlackListResponse doRemoveFromBlackList(
        @WebParam(name = "DoRemoveFromBlackListRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoRemoveFromBlackListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoRemoveItemTemplatesResponse
     */
    @WebMethod(action = "#doRemoveItemTemplates")
    @WebResult(name = "doRemoveItemTemplatesResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoRemoveItemTemplatesResponse doRemoveItemTemplates(
        @WebParam(name = "DoRemoveItemTemplatesRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoRemoveItemTemplatesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoRequestCancelBidResponse
     */
    @WebMethod(action = "#doRequestCancelBid")
    @WebResult(name = "doRequestCancelBidResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoRequestCancelBidResponse doRequestCancelBid(
        @WebParam(name = "DoRequestCancelBidRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoRequestCancelBidRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoRequestPayoutResponse
     */
    @WebMethod(action = "#doRequestPayout")
    @WebResult(name = "doRequestPayoutResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoRequestPayoutResponse doRequestPayout(
        @WebParam(name = "DoRequestPayoutRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoRequestPayoutRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoRequestSurchargeResponse
     */
    @WebMethod(action = "#doRequestSurcharge")
    @WebResult(name = "doRequestSurchargeResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoRequestSurchargeResponse doRequestSurcharge(
        @WebParam(name = "DoRequestSurchargeRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoRequestSurchargeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSellSomeAgainResponse
     */
    @WebMethod(action = "#doSellSomeAgain")
    @WebResult(name = "doSellSomeAgainResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSellSomeAgainResponse doSellSomeAgain(
        @WebParam(name = "DoSellSomeAgainRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSellSomeAgainRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSellSomeAgainInShopResponse
     */
    @WebMethod(action = "#doSellSomeAgainInShop")
    @WebResult(name = "doSellSomeAgainInShopResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSellSomeAgainInShopResponse doSellSomeAgainInShop(
        @WebParam(name = "DoSellSomeAgainInShopRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSellSomeAgainInShopRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSendEmailToUserResponse
     */
    @WebMethod(action = "#doSendEmailToUser")
    @WebResult(name = "doSendEmailToUserResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSendEmailToUserResponse doSendEmailToUser(
        @WebParam(name = "DoSendEmailToUserRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSendEmailToUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSendPostBuyFormResponse
     */
    @WebMethod(action = "#doSendPostBuyForm")
    @WebResult(name = "doSendPostBuyFormResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSendPostBuyFormResponse doSendPostBuyForm(
        @WebParam(name = "DoSendPostBuyFormRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSendPostBuyFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSendRefundFormResponse
     */
    @WebMethod(action = "#doSendRefundForm")
    @WebResult(name = "doSendRefundFormResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSendRefundFormResponse doSendRefundForm(
        @WebParam(name = "DoSendRefundFormRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSendRefundFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSetFreeDeliveryAmountResponse
     */
    @WebMethod(action = "#doSetFreeDeliveryAmount")
    @WebResult(name = "doSetFreeDeliveryAmountResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSetFreeDeliveryAmountResponse doSetFreeDeliveryAmount(
        @WebParam(name = "DoSetFreeDeliveryAmountRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSetFreeDeliveryAmountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSetShipmentPriceTypeResponse
     */
    @WebMethod(action = "#doSetShipmentPriceType")
    @WebResult(name = "doSetShipmentPriceTypeResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSetShipmentPriceTypeResponse doSetShipmentPriceType(
        @WebParam(name = "DoSetShipmentPriceTypeRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSetShipmentPriceTypeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoSetUserLicenceDateResponse
     */
    @WebMethod(action = "#doSetUserLicenceDate")
    @WebResult(name = "doSetUserLicenceDateResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoSetUserLicenceDateResponse doSetUserLicenceDate(
        @WebParam(name = "DoSetUserLicenceDateRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoSetUserLicenceDateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoShowItemInfoExtResponse
     */
    @WebMethod(action = "#doShowItemInfoExt")
    @WebResult(name = "doShowItemInfoExtResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoShowItemInfoExtResponse doShowItemInfoExt(
        @WebParam(name = "DoShowItemInfoExtRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoShowItemInfoExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoShowUserResponse
     */
    @WebMethod(action = "#doShowUser")
    @WebResult(name = "doShowUserResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoShowUserResponse doShowUser(
        @WebParam(name = "DoShowUserRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoShowUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns sandboxwebapi.DoVerifyItemResponse
     */
    @WebMethod(action = "#doVerifyItem")
    @WebResult(name = "doVerifyItemResponse", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
    public DoVerifyItemResponse doVerifyItem(
        @WebParam(name = "DoVerifyItemRequest", targetNamespace = "urn:SandboxWebApi", partName = "parameters")
        DoVerifyItemRequest parameters);

}
